server:
  port: 8080

spring:
  application:
    name: todo-app-backend

  datasource:
    url: jdbc:mysql://localhost:3306/todo
    username: ejemplo
    password: ejemplo
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true